### ISSUE TITLE
Dell XPS 15 9510  No sign of control

### ISSUE THREAD

**Issue by noenic** [AaronKelley/DellFanManagement#13]
Hi, I have a dell XPS 9510, I don't understand why but i can't do anything it looks like it just doesn't report any data that make sense...I know that 9500 and 9700 XPS series can work with it...

Here are the logs:
 **DellFanCmd 2.1
By Aaron Kelley
Licensed under GPLv3
Source code available at https://github.com/AaronKelley/DellFanManagement

Dell SMM I/O driver by 424778940z
https://github.com/424778940z/bzh-windrv-dell-smm-io

Derived from "Dell fan utility" by 424778940z
https://github.com/424778940z/dell-fan-utility

Loading SMM I/O driver...
 ...Success.
Disabling EC fan control...
Looks like fan 2 is not present, system only has one fan?
Measuring: Fan 1, level 0...
Measuring: Fan 1, level 1...
Measuring: Fan 1, level 2...
Enabling EC fan control...
Test procedure is finished.

Fan 1 initial speed: 4294967295

Fan 1 level 0 speed: 4294967295
Fan 1 level 1 speed: 4294967295
Fan 1 level 2 speed: 4294967295

Unloading SMM I/O driver...
 ...Done.**

Something is not right do you have any ideas on what it can be ?

**Comment by AaronKelley** [comment]
Currently, systems with Intel 11th-gen CPUs are not supported.  The fan control interface has changed and (AFAIK) no one has figured out how to issue commands to control it yet.  (I have had success in reading the fan RPM values, but not in changing the fan behavior at all.)

**Comment by noenic** [comment]
> 
> 
> Currently, systems with Intel 11th-gen CPUs are not supported. The fan control interface has changed and (AFAIK) no one has figured out how to issue commands to control it yet. (I have had success in reading the fan RPM values, but not in changing the fan behavior at all.)

Oh...that sucks...well..thanks for the clarification.
