### ISSUE TITLE
 NVIDIAApiException and crash of DellFanManagement after updating NVidia driver to 512.95 on Vostro 7590 / GeForce GTX 1650

### ISSUE THREAD

**Issue by bedrin** [AaronKelley/DellFanManagement#27]
I'm getting NVIDIAApiException and crash of DellFanManagement after updating NVidia driver to 512.95

![image](https://user-images.githubusercontent.com/4654384/173049577-ca5d5711-3fa5-4f4d-a3fe-705de7189502.png)

I'm using Dell Vostro 7590 with  NVidia GeForce GTX 1650

**Comment by bedrin** [comment]
Addressed by https://github.com/AaronKelley/DellFanManagement/pull/22

**Comment by AaronKelley** [comment]
Fixed.  Test version published.  See: [NBT post](https://notebooktalk.net/topic/20-dell-fan-management-%E2%80%94-software-for-controlling-the-dell-laptop-fan-speed/?do=findComment&comment=8763&_rid=67)

**Comment by Nojevah** [comment]
Hello, the link in NBT post is not working (anymore ?).
Previous beta can't be opened on Windows 11 (saying .NET 5 has reached end of life).

**Comment by AaronKelley** [comment]
I have refreshed the link on NBT.
