### ISSUE TITLE
When used under „Windows 7“ causes instant BSOD

### ISSUE THREAD

**Issue by dziugas1959** [AaronKelley/DellFanManagement#32]
While „Windows 7“ is an interesting choice to use with an 8th gen CPU, it is 100% possible and usable with special „Win7 convert“ drivers. The only 3 things in device manager that don't have a real driver are Fingerprint and Wifi+Bluetooth (But that is because I upgraded to AX210 „Wi-Fi 6“+„Bluetooth 5.2“), though sadly disabling EC doesn't work, as it causes an instant crash with bzh_dell_smm_io_x64.sys being the cause. Maybe somebody has experienced this and found a fix?

**Comment by AaronKelley** [comment]
bzh_dell_smm_io_x64.sys is intended for use on Windows 10 and up.  It is separate from this project.  The source code is here: https://github.com/424778940z/bzh-windrv-dell-smm-io
