### ISSUE TITLE
Only detecting 1 of 2 fans? 

### ISSUE THREAD

**Issue by pmojong** [AaronKelley/DellFanManagement#35]
> C:\Users\xps\Downloads\DellFanCmd-2.1.1>DellFanCmd testDellFanCmd 2.1.1
> By Aaron Kelley
> Licensed under GPLv3
> Source code available at https://github.com/AaronKelley/DellFanManagement
> 
> Dell SMM I/O driver by 424778940z
> https://github.com/424778940z/bzh-windrv-dell-smm-io
> 
> Derived from "Dell fan utility" by 424778940z
> https://github.com/424778940z/dell-fan-utility
> 
> Loading SMM I/O driver...
>  ...Success.
> Disabling EC fan control...
> Looks like fan 2 is not present, system only has one fan?
> Measuring: Fan 1, level 0...
> Measuring: Fan 1, level 1...
> Measuring: Fan 1, level 2...
> Enabling EC fan control...
> Test procedure is finished.
> 
> 
> Fan 1 initial speed: 4294967295
> 
> Fan 1 level 0 speed: 4294967295
> Fan 1 level 1 speed: 4294967295
> Fan 1 level 2 speed: 4294967295
> 
> Unloading SMM I/O driver...
>  ...Done.

Not quite sure why, I'm using the Dell XPS 15 9030, which should have two fans as opposed to one. I've already updated my BIOS & drivers but still no luck.

**Comment by AaronKelley** [comment]
It's not detecting the first fan right either (bogus fan speed reading).  This program only works with systems with 10th gen CPUs and older.  Dell changed the fan control mechanism with 11th gen.
