### ISSUE TITLE
program doesn't open

### ISSUE THREAD

**Issue by lolidkjustemo** [AaronKelley/DellFanManagement#9]
First I'm using a Inspirion 3593 and I just want to control the CPU fan I'm pretty sure that its working properly  but I'm a young lad and quite new to computers, whenever I try to start it up it quickly opens and closes CMD I have vcredist and .NET framework some guy recommended this to me and just told me to install extract an open and this is what happened

**Comment by AaronKelley** [comment]
This is a command line application and it must be used from the Windows command line.  I am working on a GUI application but it is not ready yet.
